### ISSUE TITLE
Code is not running

### ISSUE THREAD

**Issue by tanaymitkari1** [adanot/opencv3-angle-detection#2]
Traceback (most recent call last):
  File "D:/Projects/ArtificialIntelligance/angle_detection.py", line 106, in <module>
    t.run()
  File "D:/Projects/ArtificialIntelligance/angle_detection.py", line 88, in run
    cv.putText(img, str(angle), (int(x1) + 50, (int(y2) + int(y1)) / 2), font, 4, (255, 255, 255))
TypeError: integer argument expected, got float

Process finished with exit code 1

how to solve this error...!!! pls reply.
Thankyou.

**Comment by adanot** [comment]
@tanaymitkari1 it's been a while since I've used this but my initial guess is that 
`cv.putText(img, str(angle), (int(x1) + 50, (int(y2) + int(y1)) / 2), font, 4, (255, 255, 255))`
should be updated to
`cv.putText(img, str(angle), (int(x1) + 50, (int(y2) + int(y1 / 2)), font, 4, (255, 255, 255))`

Notice the parens wrapping `int(y1/2)`

Feel free to submit a PR if that is the fix.

Hope this helps!
